### ISSUE TITLE
Could you please provide the rough training time?

### ISSUE THREAD

**Issue by lemon-prog123** [QiuhongAnnaWei/LEGO-Net#5]
Hi, Great job for the rearrangement of objects. 

I try to train my own model and could you give a rough time of training process? My gpu is a nvidia gtx 3090ti. Thank you!

**Comment by QiuhongAnnaWei** [comment]
Hi so sorry about the delayed response!

The bedroom checkpoint (trained for 50000 iterations) took around 41 hours on 1 GPU, and the livingroom checkpoint (trained for 50000 iterations) took around 37 hours on 1 GPU. 

The exact specs of the GPUs are a bit hard to find now because of some changes with the cluster. I can try looking for them... Hopefully this is of some help!
